### PR TITLE
fix(rpc): allow query latest block

### LINKED ISSUE #1758: Fix CometBFT RPC compatibility
https://github.com/rollkit/rollkit/pull/224 introduced a breaking change in CometBFT RPC, where optional parameters are no longer accepted. Specifically, [this line](https://github.com/rollkit/rollkit/blob/01782daf10107d6b5856f4c3181893f3ba86584e/rpc/json/handler.go#L135) is responsible for this behavior.

As a result, queries like `/block` that used to return the latest block when `height` is not supplied now fail with `missing param 'height'`. This behavior is implemented in [this line](https://github.com/cometbft/cometbft/blob/9742bf6e1/rpc/core/env.go#L172) of CometBFT.

Until this issue is fixed, I have submitted a PR to hyperlane ([https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4096](https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4096)). Additionally, clients that use [cosmjs](https://github.com/cosmos/cosmjs/blob/e819a1fc0e/packages/tendermint-rpc/src/comet38/comet38client.ts#L93) to get the latest block will also be affected.

I'm confident that there are other clients that rely on this behavior from CometBFT, and I urge you to fix this issue.

### PR DESCRIPTION
**Pull request by tuxcanfly**
## Overview

Allow querying latest `/block` without requiring `?height=` param for CometBFT compat.

Fixes #1758 

## Summary by CodeRabbit

- **New Features**
  - Enhanced parameter handling to support `*StrInt64` type with improved error handling.

- **Bug Fixes**
  - Fixed handling of nullable `Height` parameter in `Block` function to prevent potential dereference issues.

- **Tests**
  - Updated test cases to cover scenarios for valid/malformed requests and different parameter conditions.

- **Refactor**
  - Modified `Height` field in `blockArgs` struct to use `*StrInt64` for better nullability support.

### CODE REVIEW

File: rpc/json/service_test.go [hunk 1]
```diff
@@ -64,10 +64,11 @@ func TestREST(t *testing.T) {
 		bodyContains string
 	}{
 
-		{"invalid/malformed request", "/block?so{}wrong!", http.StatusOK, int(json2.E_INVALID_REQ), ``},
-		{"invalid/missing param", "/block", http.StatusOK, int(json2.E_INVALID_REQ), `missing param 'height'`},
-		{"valid/no params", "/abci_info", http.StatusOK, -1, `"last_block_height":"345"`},
+		{"valid/malformed request", "/block?so{}wrong!", http.StatusOK, int(json2.E_INTERNAL), ``},
```
Comment (tuxcanfly) [inline rpc/json/service_test.go:67]: this is now valid as `height` is optional.

**Review by Manav-Aggarwal — APPROVED** [review]
LGTM

**Review by gupadhyaya — APPROVED** [review]

File: rpc/json/handler.go [hunk 2]
```diff
@@ -131,13 +131,17 @@ func (h *handler) newHandler(methodSpec *method) func(http.ResponseWriter, *http
 		for i := 0; i < methodSpec.argsType.NumField(); i++ {
 			field := methodSpec.argsType.Field(i)
 			name := field.Tag.Get("json")
-			if !values.Has(name) {
+			kind := field.Type.Kind()
+			// pointers can be skipped from required check
+			if kind != reflect.Pointer && !values.Has(name) {
```
Comment (assafmo) [inline rpc/json/handler.go:136]: ohh that's smart

**Comment by avious00** [comment]
thanks @Manav-Aggarwal!
