### PR TITLE
ignore validation failed error for the genesis block

### LINKED ISSUE #969: header exchange throws failed to broadcast block header error validation ignored
4:21PM ERR failed to broadcast block header error="validation ignored" module=HeaderExchangeService

### PR DESCRIPTION
**Pull request by gupadhyaya**
Fixes #969 

This PR fixes the `validation failed` error that is thrown by header and block sync, which happens when the sequencer calls `Broadcast` which also does publish the header/block locally for updating the store. This happens because the sequencer before broadcasting, for the genesis header, already does the store initialization and double store update causes this error. The prior initialization is required to start the syncer and there is no easier way to skip one of the two initializations. In future, can refactor the code to move syncer start to its own thread. But for now, ignoring the error is easier solution without adding any safety concerns.

## Summary by CodeRabbit

- **Refactor**
	- Improved handling of genesis blocks and headers during synchronization, enhancing the app's stability and reducing unnecessary error logs.

### CODE REVIEW

File: block/block_sync.go [hunk 1]
```diff
@@ -113,7 +114,13 @@ func (bSyncService *BlockSyncService) WriteToBlockStoreAndBroadcast(ctx context.
 
 	// Broadcast for subscribers
 	if err := bSyncService.sub.Broadcast(ctx, block); err != nil {
-		bSyncService.logger.Error("failed to broadcast block", "error", err)
+		// for the genesis header, broadcast error is expected as we have already initialized the store
+		// for starting the syncer. Hence, we ignore the error.
+		// exact reason: validation failed, err header verification failed: known header: '1' <= current '1'
```
Comment (MSevey) [inline block/block_sync.go:119]: if the error is expected for genesis, should we just not call broadcast? 

Or can we check for that error explicitly (the one listed in the comment) to avoid missing other potential errors returned from broadcast during genesis?

Comment (gupadhyaya) [reply block/block_sync.go:119]: broadcast is needed in the sequencer to share the produced block with p2p peers. ideally, we should not init and start the syncer and then broadcast which results in double init of the genesis block. we should only do the broadcast and trigger syncer to init after that. i have created an issue to tackle this in v1: https://github.com/rollkit/rollkit/issues/1501

with regards to catching the explicit error, unfortunately, only `validation failed` is thrown without the actual error details, hence we cannot match the exact/partial error. This is something go-header can fix and i have created an issue for it: https://github.com/celestiaorg/go-header/issues/146

Comment (Wondertan) [reply block/block_sync.go:119]: https://github.com/celestiaorg/go-header/issues/146#issuecomment-1905191830

**Comment by MSevey** [comment]
Is there a regression test we can write for this? 
This took a long time to debug and resolve, so I'd hate for us to inadvertently re-introduce this as a failure mode in the future.

**Comment by gupadhyaya** [comment]
> Is there a regression test we can write for this? This took a long time to debug and resolve, so I'd hate for us to inadvertently re-introduce this as a failure mode in the future.

tighten the error skip logic to skip only ValidationFailed. this is the best we can do given that exact reason for validation failure (`known header: '1' <= current '1'`) is not propagated. however this would still help not skip many useful errors.

i did want to add additional efforts into this as we are tackling https://github.com/rollkit/rollkit/issues/1501 in v1 and it should totally remove this error skipping logic.

let me know if this works.

**Review by MSevey — APPROVED** [review]

**Review by Manav-Aggarwal — APPROVED** [review]
