### PR TITLE
fix: store lastBatchHash & fix header/data broadcast

### LINKED ISSUE #1972: bug: lastBatchHash only stored in-memory leading to mismatch after restart
the lastBatchHash is stored only in-memory: https://github.com/rollkit/rollkit/blob/main/block/manager.go#L446
this leads to following error if the node stops and restarts
```
6:24PM ERR error while retrieving batch error="rpc error: code = Unknown desc = batch hash mismatch: lastBatchHash = bb38c42f9c5965ecc3efffd764773e0cc2f8abb850ba1b279cb7579c6ab55b6e, req.LastBatchHash = " module=BlockManager
```

solution is to persist the lastBatchHash to store and load it on restart.

### PR DESCRIPTION
**Pull request by facundomedica**
## Overview

Closes #1972

We also fix another case in which when broadcasting to the go-header sub the first time after a restart, it would make the server hang forever

## Summary by CodeRabbit

- **New Features**
  - Enhanced the system’s capability to persist processing state between data batches, ensuring consistent operations.
- **Bug Fixes**
  - Refined the initial synchronization process to more gracefully handle expected startup conditions, reducing unnecessary error notifications.

### CODE REVIEW

**Review by yarikbratashchuk — APPROVED** [review]
makes sense

File: block/manager.go [hunk 1]
```diff
@@ -443,6 +455,11 @@ func (m *Manager) BatchRetrieveLoop(ctx context.Context) {
 
 					// Update lastBatchHash only if the batch contains transactions
 					if batch.Transactions != nil {
+						err := m.store.SetMetadata(ctx, LastBatchHashKey, h)
```
Comment (gupadhyaya) [inline block/manager.go:458]: do you think we can avoid writing to disk on every update? i think we can keep it in-memory and only write to db upon shutdown? how about moving this to:
```
func (n *FullNode) OnStop()
```
and calling `n.blockManager.Stop()` and inserting this update logic in the `Stop()` method? 
trying to avoid expensive disk writes.

File: block/manager.go [hunk 2]
```diff
@@ -424,6 +427,15 @@ func (m *Manager) BatchRetrieveLoop(ctx context.Context) {
 				return
 			}
 
+			// If lastBatchHash is not set, retrieve the last batch hash from store
+			if m.lastBatchHash == nil {
```
Comment (gupadhyaya) [inline block/manager.go:431]: you don't need to do this in the BatchRetrieveLoop right? this can be done once in the NewManager?

File: block/sync_service.go [hunk 3]
```diff
@@ -131,18 +131,26 @@ func (syncService *SyncService[H]) WriteToStoreAndBroadcast(ctx context.Context,
...
 	// Broadcast for subscribers
 	if err := syncService.sub.Broadcast(ctx, headerOrData); err != nil {
-		// for the genesis header, broadcast error is expected as we have already initialized the store
-		// for starting the syncer. Hence, we ignore the error.
-		// exact reason: validation failed, err header verification failed: known header: '1' <= current '1'
-		if isGenesis && errors.Is(err, pubsub.ValidationError{Reason: pubsub.RejectValidationFailed}) {
+		// for the first block when starting the app, broadcast error is expected
+		// as we have already initialized the store for starting the syncer.
+		// Hence, we ignore the error. Exact reason: validation ignored
+		if (firstStart && errors.Is(err, pubsub.ValidationError{Reason: pubsub.RejectValidationIgnored})) ||
```
Comment (gupadhyaya) [inline block/sync_service.go:149]: can you elaborate on why the first start of the syncer leads to `RejectValidationIgnored`?

Comment (facundomedica) [reply block/sync_service.go:149]: This is an error that was coming up in go-header, similar to the other one there. I can't really explain it tbh

File: block/manager.go (hunk 2 above)
Comment (facundomedica) [reply block/manager.go:431]: You are right, I can move this out 👌

File: block/manager.go (hunk 1 above)
Comment (facundomedica) [reply block/manager.go:458]: opened an issue https://github.com/rollkit/rollkit/issues/1993

**Review by gupadhyaya — APPROVED** [review]
