### PR TITLE
fix: health endpoint now detects stopped block production

### LINKED ISSUE #2643: bug: health endpoint still reports OK when node has stopped producing blocks.
we should show failure when there is an error with the node.

### PR DESCRIPTION
**Pull request by randygrok**
This commit fixes issue #2643 where the health endpoint still reports OK when a node has stopped producing blocks.

Closes #2643

## Overview

Needs merge and tag of tastora PR https://github.com/celestiaorg/tastora/pull/149

### CODE REVIEW

File: pkg/rpc/server/server.go [hunk 1]
```diff
@@ -28,6 +28,16 @@ import (
...
 )
 
+const (
+	// healthCheckWarnMultiplier is the multiplier for block time to determine WARN threshold
+	// If no block has been produced in (blockTime * healthCheckWarnMultiplier), return WARN
+	healthCheckWarnMultiplier = 3
+
+	// healthCheckFailMultiplier is the multiplier for block time to determine FAIL threshold
+	// If no block has been produced in (blockTime * healthCheckFailMultiplier), return FAIL
+	healthCheckFailMultiplier = 5
```
Comment (tac0turtle) [inline pkg/rpc/server/server.go]: we should double check with @auricom if this is good or too fast

File: pkg/rpc/server/server.go [hunk 2]
```diff
@@ -288,19 +298,76 @@ func (p *P2PServer) GetNetInfo(
...
+					Time("last_block_time", state.LastBlockTime).
+					Msg("Health check: block production is slow (WARN)")
+				return connect.NewResponse(&pb.GetHealthResponse{
+					Status: pb.HealthStatus_WARN,
+				}), nil
+			}
+		}
+	}
+
+	// For non-aggregator nodes or if checks pass, return healthy
```
Comment (tac0turtle) [inline pkg/rpc/server/server.go]: we should have something with syncing for non aggregator nodes as well. maybe a follow up.

File: pkg/rpc/server/server.go (hunk 1 above)
Comment (auricom) [reply pkg/rpc/server/server.go]: This would mean for chains with a block time of 250ms, a node can only tolerate approximately 1 second of random hang time before the sequencer would be flagged as an eligible candidate for hard process termination.

We might improve safety by using an absolute timeout threshold (in seconds) rather than a configuration-relative value. This would provide more predictable failure detection across different chain configurations.

I'd say 3-5 seconds would be ok BUT I believe we should hear @alpe's perspective on what constitutes an appropriate timeout threshold before forcing a sequencer in an HA cluster to be considered stale, so leadership can be transferred to another.

**Comment by auricom** [comment]
A healthcheck endpoint is used by infrastructure automation to determine if a process can respond to client requests.

AFAIK based on this PR, the existing endpoint did not perform substantive validation.

For a node to be considered healthy, the following conditions should be met:

1- The RPC server is operational and responds correctly to basic client queries per specifications
2- The aggregator is producing blocks at the expected rate
3- The full node is synchronizing with the network
4- The P2P network is ready to accept incoming connections (if enabled)

I cannot verify whether this change effectively validates items 1 and 4. And I may be overly cautious, so I would appreciate your expertise on these points :technologist:

**Comment by randygrok** [comment]
thanks @auricom , let me check those points.

By your definition only point 2 is covered

File: pkg/rpc/client/client.go [hunk 3]
```diff
@@ -114,14 +145,90 @@ func (c *Client) GetNetInfo(ctx context.Context) (*pb.NetInfo, error) {
...
 }
 
-// GetHealth calls the HealthService.Livez endpoint and returns the HealthStatus
-func (c *Client) GetHealth(ctx context.Context) (pb.HealthStatus, error) {
-	req := connect.NewRequest(&emptypb.Empty{})
-	resp, err := c.healthClient.Livez(ctx, req)
+// GetHealth calls the /health/live HTTP endpoint and returns the HealthStatus
+// This endpoint checks liveness (is the process alive and responsive?).
+// For readiness checks (can the node serve correct data?), use GetReadiness().
+func (c *Client) GetHealth(ctx context.Context) (HealthStatus, error) {
```
Comment (tac0turtle) [inline pkg/rpc/client/client.go]: are these needed? its a curl call, having wrappers for curl seem overkill if we document the api itself.

File: pkg/rpc/server/http.go [hunk 4]
```diff
@@ -15,42 +23,91 @@ type BestKnownHeightProvider func() uint64
...
 // Additional custom HTTP endpoints can be registered on the mux here.
-func RegisterCustomHTTPEndpoints(mux *http.ServeMux, s store.Store, pm p2p.P2PRPC, cfg config.Config, bestKnownHeightProvider BestKnownHeightProvider) {
+//
+// For detailed documentation on health endpoints, see: docs/learn/config.md#health-endpoints
+func RegisterCustomHTTPEndpoints(mux *http.ServeMux, s store.Store, pm p2p.P2PRPC, cfg config.Config, bestKnownHeightProvider BestKnownHeightProvider, logger zerolog.Logger) {
+	// Liveness endpoint - checks if the service process is alive and responsive
+	// A failing liveness check should result in killing/restarting the process
+	// This endpoint should NOT check business logic (like block production or sync status)
+	//
+	// See docs/learn/config.md#healthlive---liveness-probe for details
```
Comment (tac0turtle) [inline pkg/rpc/server/http.go]: can we remove some of this ai slop comments?

File: pkg/rpc/server/http.go [hunk 5]
```diff
@@ -15,42 +23,91 @@ type BestKnownHeightProvider func() uint64
...
+				peers, err := pm.GetPeers()
+				if err != nil {
+					http.Error(w, "UNREADY: failed to query peers", http.StatusServiceUnavailable)
+					return
+				}
+				if len(peers) == 0 {
+					http.Error(w, "UNREADY: no peers connected", http.StatusServiceUnavailable)
+					return
+				}
+			}
```
Comment (tac0turtle) [inline pkg/rpc/server/http.go:77]: i dont get this change?

File: pkg/rpc/server/http.go [hunk 6]
```diff
@@ -15,42 +23,91 @@ type BestKnownHeightProvider func() uint64
...
+		// Aggregator block production check: verify blocks are being produced at expected rate
+		if cfg.Node.Aggregator {
+			timeSinceLastBlock := time.Since(state.LastBlockTime)
+			maxAllowedDelay := 5 * cfg.Node.BlockTime.Duration
+
+			if timeSinceLastBlock > maxAllowedDelay {
+				http.Error(w, "UNREADY: aggregator not producing blocks at expected rate", http.StatusServiceUnavailable)
+				return
+			}
+		}
```
Comment (tac0turtle) [inline pkg/rpc/server/http.go:100]: this doesnt seem to cover the extent that claude mentioned in his comment.

**Review by tac0turtle — COMMENTED** [review]
this is a good start but doesnt solve the issue at hand

File: pkg/rpc/server/http.go (hunk 5 above)
Comment (randygrok) [reply pkg/rpc/server/http.go:77]: this was already there before. 

We don't consider ready a non aggregator node that does not contain any peer.

@auricom do you think this is correct?

**Comment by randygrok** [comment]
@auricom take a look specifically into the server endpoints

File: pkg/rpc/server/http.go (hunk 5 above)
Comment (auricom) [reply pkg/rpc/server/http.go:77]: That totally makes sense for me:

Let's imagine this situation.

gateway is running 10 fullnodes behind its `https://rpc.eden.gateway.io` url
one of the fullnode loses connection to other peers => it will experience latency and would not be able to forward transactions
So this node needs to be booted from the fullnodes pool so that users won't interact with a unready node.

**Comment by auricom** [comment]
the included documentation does seem to be what we want to achieve, thanks

but i'm not sure the ready endpoint is working as intended

ran a fullnode on eden testnet using `ghcr.io/evstack/ev-node-evm-single:pr-2800`

```
evm-single start  --evm.jwt-secret-file /root/jwt/jwt.hex --evm.genesis-hash 0x915128c096aac37917bd6b987190ee22d9f1c8421b990c5896a6b300795fab90 --evm.engine-url http://localhost:18551 --evm.eth-url http://localhost:18555 --evnode.da.address http://100.123.142.81:36658 --home=/root/.evm-single --evnode.rpc.address=0.0.0.0:7341 --evnode.instrumentation.prometheus --evnode.instrumentation.prometheus_listen_addr=:26670
```

node was configured without p2p peer and with wrong namespaces (so it wasnt able to da sync)


```
ev-node-1   | 1:03PM INF initialized syncer state chain_id=edennet-2 component=syncer da_height=7970386 height=0
ev-node-1   | 1:03PM INF syncer started component=syncer
ev-node-1   | 1:03PM INF starting process loop component=syncer
ev-node-1   | 1:03PM INF starting sync loop component=syncer
ev-node-1   | 1:03PM INF starting DA inclusion processing loop component=submitter
```

node was stuck on block 0 with 0 peer but ready endpoint was considered `READY`

curl -v http://localhost:7331/health/ready
* Host localhost:7331 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:7331...
* Established connection to localhost (::1 port 7331) from ::1 port 39896 
* using HTTP/1.x
> GET /health/ready HTTP/1.1
> Host: localhost:7331
> User-Agent: curl/8.17.0
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Fri, 07 Nov 2025 13:07:19 GMT
< Content-Length: 6
< 
READY
* Connection #0 to host localhost:7331 left intact

**Comment by randygrok** [comment]
thanks for the message, let me check, this is helpful

**Comment by auricom** [comment]
turns out that was issues coming from my workstation. Can confirm that unready node was detected unready on the endpoint

**Review by auricom — APPROVED** [review]
