### PR TITLE
test: fix test Lazy aggregator, fast da sync, two rollups same namespace

### LINKED ISSUE #1812: test: adapt TestTwoRollupsInOneNamespace after header and data separation

### PR DESCRIPTION
**Pull request by gupadhyaya**
Fixes #1812 #1819 #1857 

## Summary by CodeRabbit

- **New Features**
	- Enhanced synchronization process for handling empty transactions, allowing smoother operations without waiting for data.
	- Added a notification mechanism for batch processing, improving responsiveness in transaction handling.
	- Implemented new tests for lazy aggregation, fast data synchronization, and rollup behavior, improving overall testing coverage.

- **Bug Fixes**
	- Clarified error messages in the data verification process to improve understanding of issues.

- **Chores**
	- Activated the `safeClose` function to ensure proper channel management.

### CODE REVIEW

File: block/batch.go [hunk 1]
```diff
@@ -6,14 +6,16 @@ import (
 
 // BatchQueue is a queue of transaction batches with timestamps
 type BatchQueue struct {
-	queue []BatchWithTime
-	mu    sync.Mutex
+	queue    []BatchWithTime
+	mu       sync.Mutex
+	notifyCh chan struct{}
```
Comment (gupadhyaya) [inline block/batch.go:11]: introduced notification to batch for using in case of lazy aggregator instead of mempool txsAvailable

File: block/manager.go [hunk 2]
```diff
@@ -78,6 +78,8 @@ var initialBackoff = 100 * time.Millisecond
 // DAIncludedHeightKey is the key used for persisting the da included height in store.
 const DAIncludedHeightKey = "da included height"
 
+var dataHashForEmptyTxs = []byte{110, 52, 11, 156, 255, 179, 122, 152, 156, 165, 68, 230, 187, 120, 10, 44, 120, 144, 29, 63, 179, 55, 56, 118, 133, 17, 163, 6, 23, 175, 160, 29}
```
Comment (gupadhyaya) [inline block/manager.go:81]: introduced `dataHashForEmptyTxs` to be used while only syncing headers from DA and no p2p to get the Data for no txs scenarios, the syncing can proceed without getting stuck forever.

File: block/batch.go [hunk 3]
```diff
@@ -6,14 +6,16 @@ import (
...
 }
 
 // NewBatchQueue creates a new BatchQueue
 func NewBatchQueue() *BatchQueue {
 	return &BatchQueue{
-		queue: make([]BatchWithTime, 0),
+		queue:    make([]BatchWithTime, 0),
+		notifyCh: make(chan struct{}, 1), // Buffered channel to avoid blocking
```
Comment (MSevey) [inline block/batch.go:18]: The buffer doesn't prevent blocking. You still need to use select statements. 
An empty channel is just useless because you can never put anything into it. 

https://go.dev/play/p/wPvDbnaX983

I'd remove the comment as it is inaccurate.

File: block/manager.go (hunk 2 above)
Comment (MSevey) [reply block/manager.go:81]: I'd add this a comment.

File: block/manager.go [hunk 4]
```diff
@@ -607,6 +600,34 @@ func (m *Manager) SyncLoop(ctx context.Context, cancel context.CancelFunc) {
 			m.sendNonBlockingSignalToHeaderStoreCh()
 			m.sendNonBlockingSignalToRetrieveCh()
 
+			// check if the dataHash is dataHashForEmptyTxs
+			// no need to wait for syncing Data, instead prepare now and set
+			// so that trySyncNextBlock can progress
+			if bytes.Equal(header.DataHash, dataHashForEmptyTxs) {
```
Comment (MSevey) [inline block/manager.go:606]: [non-blocking]
I think it is worthwhile making this a small helper function for this comparison so that it has a unit test where the bytes are hardcoded in the test. This would protect against the bytes changing and impacting this internal function logic.

File: node/helpers.go [hunk 5]
```diff
@@ -96,13 +96,13 @@ func getNodeHeightFromStore(node Node) (uint64, error) {
...
-// 		close(ch)
-// 	}
-// }
+func safeClose(ch chan struct{}) {
+	select {
+	case <-ch:
+	default:
+		close(ch)
+	}
+}
```
[the remark this answers is not in the document]
Comment (MSevey) [reply node/helpers.go:105]: [non blocking] good first issue as a follow up to apply this to all locations of close in testing.

File: block/batch.go [hunk 6]
```diff
@@ -35,3 +42,8 @@ func (bq *BatchQueue) Next() *BatchWithTime {
 	bq.queue = bq.queue[1:]
 	return &batch
 }
+
+// NotifyCh returns the notification channel
+func (bq *BatchQueue) NotifyCh() <-chan struct{} {
```
Comment (MSevey) [inline block/batch.go:47]: is this actually called anywhere? I don't think I saw it used, in which case we should just remove it.

**Review by MSevey — CHANGES_REQUESTED** [review]
Some minor updates to include when resolving the merge conflicts.

**Review by MSevey — DISMISSED** [review]

File: block/manager.go [hunk 7]
```diff
@@ -563,6 +557,34 @@ func (m *Manager) HeaderSubmissionLoop(ctx context.Context) {
...
 }
 
+func (m *Manager) handleEmptyDataHash(ctx context.Context, header *types.Header) {
+	headerHeight := header.Height()
+	if bytes.Equal(header.DataHash, dataHashForEmptyTxs) {
+		var lastDataHash types.Hash
+		var err error
+		var lastData *types.Data
+		if headerHeight > 1 {
+			_, lastData, err = m.store.GetBlockData(ctx, headerHeight-1)
```
Comment (tuxcanfly) [inline block/manager.go:567]: [non blocking] Is err here due to out of order sync? Should we log it at debug level to help trace the execution path in future?

File: block/manager_test.go [hunk 8]
```diff
@@ -130,6 +130,53 @@ func TestInitialStateStored(t *testing.T) {
...
+
+	// Setup the manager with the mock and data cache
+	m := &Manager{
+		store:     store,
+		dataCache: dataCache,
+	}
+
+	// Define the test data
+	headerHeight := 2
+	dataHashForEmptyTxs := []byte{110, 52, 11, 156, 255, 179, 122, 152, 156, 165, 68, 230, 187, 120, 10, 44, 120, 144, 29, 63, 179, 55, 56, 118, 133, 17, 163, 6, 23, 175, 160, 29}
```
Comment (tuxcanfly) [inline block/manager_test.go:149]:
```suggestion
```

**Review by tuxcanfly — APPROVED** [review]
OK, with some minor nits.

**Review by tuxcanfly — APPROVED** [review]
OK.

**Review by tzdybal — COMMENTED** [review]
I don't like the `dataHashForEmptyTxs`. Can't think about anything significantly prettier.

File: block/manager.go [hunk 9]
```diff
@@ -78,6 +78,9 @@ var initialBackoff = 100 * time.Millisecond
 // DAIncludedHeightKey is the key used for persisting the da included height in store.
 const DAIncludedHeightKey = "da included height"
 
+// dataHashForEmptyTxs to be used while only syncing headers from DA and no p2p to get the Data for no txs scenarios, the syncing can proceed without getting stuck forever.
+var dataHashForEmptyTxs = []byte{110, 52, 11, 156, 255, 179, 122, 152, 156, 165, 68, 230, 187, 120, 10, 44, 120, 144, 29, 63, 179, 55, 56, 118, 133, 17, 163, 6, 23, 175, 160, 29}
```
[the remark this answers is not in the document]
Comment (gupadhyaya) [reply block/manager.go:82]: It is constant because it is hash of empty `Data` with no `txs` and no `Metadata`. Yes, the `Metadata` is only used for p2p sync.

**Review by tzdybal — APPROVED** [review]
