### PR TITLE
fix: start signer path

### LINKED ISSUE #2603: Flag evnode.signer.path not respected
## Summary

When initialising evnode with `--evnode.signer.path /config/signer.json`, the flag is not respected. 

The `evnode.yml` file still contains the default:
```yaml
signer:
  # Type of remote signer to use (file, grpc)
  signer_type: file
  # Path to the signer file or address
  signer_path: /root/.evm-single/config
``` 

When evnode is started using the same flag, the `Header` and `Data` payloads are signed by the key in the default path, and not in the flag provided path.

#### Version

ghcr.io/evstack/ev-node-evm-single:main

```
...
"Id": "sha256:0ff1ff06cc3e9d74d59a7c53d883685cd93e210bec2db48485b9cea2c10c7af4",
        "RepoTags": [
            "ghcr.io/evstack/ev-node-evm-single:main"
        ],
        "RepoDigests": [
            "ghcr.io/evstack/ev-node-evm-single@sha256:85df65239cf49e7fe96e7e5a24a909a48e8b17a79cf03c4d4a00b854a8470bc8"
        ],
...
```

### System Information

Docker

### Network Configuration

_No response_

### Development Environment

_No response_

### Configuration Details

_No response_

### Steps to Reproduce

above

### Expected Result

above

### Actual Result

above

### Relevant Logs

```Shell

```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tac0turtle**
## Overview

closes #2603

make relative path work with start command

### CODE REVIEW

File: pkg/cmd/run_node.go [hunk 1]
```diff
@@ -96,10 +96,20 @@ func StartNode(
 			return err
 		}
 
-		// Resolve signer path relative to root directory if it's not an absolute path
+		// Resolve signer path; allow absolute, relative to node root, or relative to CWD if resolution fails
 		signerPath := nodeConfig.Signer.SignerPath
 		if !filepath.IsAbs(signerPath) {
-			signerPath = filepath.Join(nodeConfig.RootDir, signerPath)
```
Comment (julienrbrt) [inline pkg/cmd/run_node.go:102]: I think, we can just do `strings.TrimSuffix(signerPath, "signer.json")` at line 101, as the filename is forced to be `signer.json` in `LoadFileSystemSigner`.

**Review by julienrbrt — DISMISSED** [review]

**Review by julienrbrt — APPROVED** [review]
