### PR TITLE
fix: inconsistent state detection and rollback

### LINKED ISSUE #2967: Improve EVM rollback
ev-reth rollback command only rollbacks ev-node. We use the ev-reth behavior that automatically rollbacks when the consensus sends an earlier head. This is different from ev-abci, where we rollback directly from the command: https://github.com/evstack/ev-abci/blob/main/server/rollback_cmd.go#L91-L95.

With https://github.com/evstack/ev-node/pull/2966 change, the evm rollback command won't work, as ev-reth will be ahead and you won't be able to restart (as hitting the inconsistent state error). The rollback must be manual.

We should update the EVM rollback command to do the payload re-submission directly in the rollback command. To effectively rollback both ev-reth and ev-node. This is slightly breaking as ev-reth and ev-node both need to be started to perform a rollback

### PR DESCRIPTION
**Pull request by alpe**
Resolves #2967

## Overview

* Also check timestamp for Idempotency 
* Implement rollback for evm EngineClient

### CODE REVIEW

File: execution/evm/execution.go [hunk 1]
```diff
@@ -690,35 +696,57 @@ func (c *EngineClient) ResumePayload(ctx context.Context, payloadIDBytes []byte)
...
 	execMeta, err := c.store.GetExecMeta(ctx, height)
 	if err == nil && execMeta != nil {
-		// If we already have a promoted block at this height, return the stored StateRoot
+		// If we already have a promoted block at this height, verify timestamp matches
+		// to catch Dual-Store Conflicts where ExecMeta was saved for an old block
+		// that was later replaced via Raft consensus.
 		if execMeta.Stage == ExecStagePromoted && len(execMeta.StateRoot) > 0 {
-			c.logger.Info().
+			if execMeta.Timestamp == timestamp.Unix() {
+				c.logger.Info().
```
Comment (alpe) [inline execution/evm/execution.go:715]: This is still a weak check without hash but it fixed the problems on restart

File: execution/evm/execution.go [hunk 2]
```diff
@@ -907,6 +954,48 @@ func (c *EngineClient) GetLatestHeight(ctx context.Context) (uint64, error) {
 	return header.Number.Uint64(), nil
 }
 
+// Rollback resets the execution layer head to the specified height using forkchoice update.
+// This is used for recovery when the EL is ahead of the consensus layer (e.g., during rolling restarts
+// where the EL committed blocks that were not replicated to Raft).
+//
+// Implements the execution.Rollbackable interface.
+func (c *EngineClient) Rollback(ctx context.Context, targetHeight uint64) error {
```
Comment (julienrbrt) [inline execution/evm/execution.go:958]: Could we wire the command directly then? 
This would fix https://github.com/evstack/ev-node/issues/2967.

For consitency, a good follow-up would be to implement this in ev-abci and use it in the rollback command as well instead of directly calling: https://github.com/evstack/ev-abci/blob/e905b0b/server/rollback_cmd.go#L91-L95.

Comment (alpe) [reply execution/evm/execution.go:958]: 👍 I have added it to the rollback cmd.
Not started abci. I will DM you.

File: execution/evm/execution.go [hunk 3]
```diff
@@ -166,6 +172,7 @@ type EngineClient struct {
 	store *EVMStore
 
 	mu                        sync.Mutex             // Mutex to protect concurrent access to block hashes
+	forkchoiceMu              sync.Mutex             // Serializes forkchoice RPC calls to ensure EL state matches internal state
```
Comment (tac0turtle) [inline execution/evm/execution.go]: i dont believe this is needed. are we worried about parallel calls to update forkchoice rule?

File: execution/evm/execution.go [hunk 4]
```diff
@@ -744,12 +777,31 @@ func (c *EngineClient) checkIdempotency(ctx context.Context, height uint64, time
 
 			return existingStateRoot.Bytes(), nil, true, nil
 		}
-		// Timestamp mismatch - log warning but proceed
+		// Timestamp mismatch - this indicates a Dual-Store Conflict where the EL produced a block
+		// that was not replicated via Raft before leadership changed. The new leader created a
+		// different block at the same height with a different timestamp, and that block is now
```
Comment (tac0turtle) [inline execution/evm/execution.go]: could we reduce some of these comments

File: execution/evm/execution.go (hunk 3 above)
Comment (alpe) [reply execution/evm/execution.go]: This was feedback from AI. But you are right, this is a deterministic system. Good 👀

**Review by julienrbrt — APPROVED** [review]
lgtm!

File: execution/evm/execution.go [hunk 5]
```diff
@@ -907,6 +951,48 @@ func (c *EngineClient) GetLatestHeight(ctx context.Context) (uint64, error) {
 	return header.Number.Uint64(), nil
 }
 
+// Rollback resets the execution layer head to the specified height using forkchoice update.
+// This is used for recovery when the EL is ahead of the consensus layer (e.g., during rolling restarts
+// where the EL committed blocks that were not replicated to Raft).
+//
```
Comment (tac0turtle) [inline execution/evm/execution.go:956]: can this function be called while the node is running?

Comment (julienrbrt) [reply execution/evm/execution.go:956]: For EVM yes (as it resends a payload), for the SDK no. (and our DM discussion https://github.com/evstack/ev-node/pull/2983#discussion_r2697990618, showed that ev-abci won't implement it)
So maybe we should add that only execution layer supporting _in-flight_ rollback should implement this then?

Comment (tac0turtle) [reply execution/evm/execution.go:956]: do we want inflight? is that a goal for later on?

Comment (julienrbrt) [reply execution/evm/execution.go:956]: Well this is done in-flight right in this PR, so yeah: https://github.com/evstack/ev-node/pull/2983/changes#diff-73d38fc0f126d3d764a9855162c561f8a2cfe9595029aa13f510ab5937885d2dR784-R796

Comment (alpe) [reply execution/evm/execution.go:956]: I have updated the doc to mention in-flight updates on the interface.
This method is used during startup reconcile only. 
Another use-case could be within HA when the leader lock is lost during block production. But this is an edge case.
