### PR TITLE
fix: recover on restart

### LINKED ISSUE #2220: [bug]: sequencer hangs without any errors
### Version Information

- cosmos-sdk-starter v0.2.0-rc.0.0.20250213071856-219112f7d9d8
- cosmos-sdk-starter/sdk v0.0.0-20250121103458-82c819c78b1f
- rollkit v0.14.2-0.20250124093236-1f92a170f22d
- go-da v0.9.0
- go-sequencing v0.4.1

### System Information

- Operating System: Ubuntu 24.04.2 LTS
- Kernel: Linux 6.8.0-57-generic
- x86-64
- 6-core AMD Ryzen 5 
- Mem 64Gb

### Network Configuration

- testnet
- cyber42-1
- rpc/app/grpc - x.cyber-rollup.chatcyber.ai

### Development Environment

ghcr.io/rollkit/go-sequencing:baaef46
ghcr.io/rollkit/local-da:cff7abd

### Configuration Details

- DA Config - None
- Sequencer Config - None

### Steps to Reproduce

0. cyber init/gentx/collect
1. Launch https://github.com/cyborgshead/cyber-rollup/blob/main/docker-compose.yml (volume mounts to ~/.cyber)

### Expected Result

Everything works, block by block

### Actual Result

Stuck every ~100-200 blocks

### Relevant Logs

```Shell
chain:

3:13PM INF indexed block events height=884 module=txindex
3:13PM INF Creating and publishing block height=885 module=BlockManager
3:13PM INF finalized block block_app_hash=43FD83854EAA6319E778E8E691148E2B630C63A2FC4806CC768C2DC0315A3F49 height=885 module=BlockManager num_txs_res=0 num_val_updates=0
3:13PM INF executed block app_hash=43FD83854EAA6319E778E8E691148E2B630C63A2FC4806CC768C2DC0315A3F49 height=885 module=BlockManager
3:13PM INF indexed block events height=885 module=txindex
3:13PM INF Creating and publishing block height=886 module=BlockManager
3:13PM INF finalized block block_app_hash=19642E9F37906F2F9DBCA387CD3668899EAB3A66D51E379E7A6484ED4720B173 height=886 module=BlockManager num_txs_res=0 num_val_updates=0
3:13PM INF executed block app_hash=19642E9F37906F2F9DBCA387CD3668899EAB3A66D51E379E7A6484ED4720B173 height=886 module=BlockManager
3:13PM INF indexed block events height=886 module=txindex
3:13PM INF successfully submitted Rollkit headers to DA layer daHeight=60 gasPrice=-1 headerCount=13 module=BlockManager


local-da

2025/04/23 16:15:54 Listening on: 0.0.0.0:7980


go-sequencing:

2025/04/23 16:15:54 Listening on: 0.0.0.0:50051


after container restart:

3:13PM INF successfully submitted Rollkit headers to DA layer daHeight=60 gasPrice=-1 headerCount=13 module=BlockManager
3:57AM INF caught signal module=server signal=terminated
3:57AM INF stopping API server... address=tcp://0.0.0.0:1317 module=api-server
3:57AM INF stopping gRPC server... address=0.0.0.0:9090 module=grpc-server
2025-04-26T03:57:01.785Z	ERROR	header/p2p	p2p/subscriber.go:176	verifier was not set before incoming header verification	{"from": "<peer.ID 12*THfpmf>"}
2025-04-26T03:57:01.785Z	ERROR	header/p2p	p2p/subscriber.go:176	verifier was not set before incoming header verification	{"from": "<peer.ID 12*THfpmf>"}
3:57AM INF RPC HTTP server stopped err="accept tcp [::]:1317: use of closed network connection" module=api-server
3:57AM ERR failed to broadcast: validation ignored module=server
3:57AM ERR failed to broadcast: validation ignored module=server
3:57AM INF service stop impl=Node module=server msg="Stopping Node service"
3:57AM INF halting full node... module=server
3:57AM INF shutting down full node sub services... module=server
3:57AM INF service stop impl=IndexerService module=txindex msg="Stopping IndexerService service"
service cosmos.adminmodule.adminmodule.Msg does not have cosmos.msg.v1.service proto annotation
service cosmos.adminmodule.adminmodule.Msg does not have cosmos.msg.v1.service proto annotation
3:57AM INF starting node with ABCI CometBFT in-process module=server
3:57AM INF starting node with Rollkit in-process module=server
3:57AM INF service start impl=multiAppConn module=proxy msg="Starting multiAppConn service"
3:57AM INF service start connection=query impl=localClient module=abci-client msg="Starting localClient service"
3:57AM INF service start connection=snapshot impl=localClient module=abci-client msg="Starting localClient service"
3:57AM INF service start connection=mempool impl=localClient module=abci-client msg="Starting localClient service"
3:57AM INF service start connection=consensus impl=localClient module=abci-client msg="Starting localClient service"
3:57AM INF service start impl=EventBus module=events msg="Starting EventBus service"
3:57AM INF service start impl=PubSub module=pubsub msg="Starting PubSub service"
3:57AM INF Using default mempool ttl MempoolTTL=25 module=BlockManager
3:57AM INF service start impl=IndexerService module=txindex msg="Starting IndexerService service"
3:57AM INF service start impl=RPC module=server msg="Starting RPC service"
3:57AM INF service start impl=Node module=server msg="Starting Node service"
3:57AM INF starting P2P client module=server
```

### Additional Information

On my local machine everything is working (mac m1 / 15.3), but first testnet deployment on remote server failed and had given issues

https://github.com/cyborgshead/cyber-rollup
https://github.com/cyborgshead/cyber-rollup/blob/main/docker-compose.yml

### PR DESCRIPTION
**Pull request by alpe**
Resolves #2220

tlDr; Payloads require sequential height when send to the pubsub topics. Failed on gaps after restart. 

* Buffers in `HeaderCh, DataCh` were not persisted
* The `syncService.Close` method never completed successfully due to timeout and non empty topic subscribers. This lead to data loss
* Any error during `WriteToStoreAndBroadcast` was closing the consumer loop only,  not the app
* On graceful shutdown, not waited for the Go routines (producers/consumers) which caused data loss

The `TestSlowConsumers` replicates the behaviour that I have seen on my box. When the heights have gaps after restart, the channel consumers in `node/full.go` stop their work and everything freezes.

With `TestHeaderSyncServiceRestart`, I confirm that the go-headers store is persisting the data when submitted.

## Summary by CodeRabbit

- **New Features**
  - Improved block broadcasting with enhanced modularity and error handling.
  - Added robust tests simulating slow consumers and verifying persistence across restarts.
  - Enhanced synchronization service with explicit subscription management and restart tests.
  - Improved node process management in end-to-end tests, including command-based tracking and graceful shutdown.

- **Bug Fixes**
  - Ensured all background tasks complete before node shutdown for safer operation.
  - Fixed potential issues with process cleanup and synchronization during tests.

- **Refactor**
  - Replaced direct channel usage with broadcaster interfaces for block publishing.
  - Streamlined goroutine management and error handling in node operations.
  - Simplified and improved test setup and teardown procedures.

- **Chores**
  - Updated dependencies to explicitly require key libraries.
  - Reorganized import statements for clarity.

### CODE REVIEW

File: block/manager.go [hunk 1]
```diff
@@ -647,24 +651,14 @@ func (m *Manager) publishBlockInternal(ctx context.Context) error {
...
-	// event separately is due to the inconsistent nature of the select
-	// statement when multiple cases are satisfied.
-	select {
-	case <-ctx.Done():
-		return fmt.Errorf("unable to send header and block, context done: %w", ctx.Err())
-	default:
+	g, ctx := errgroup.WithContext(ctx)
+	g.Go(func() error { return m.headerBroadcaster.WriteToStoreAndBroadcast(ctx, header) })
+	g.Go(func() error { return m.dataBroadcaster.WriteToStoreAndBroadcast(ctx, data) })
+	if err := g.Wait(); err != nil {
```
Comment (alpe) [inline block/manager.go:657]: This will block and fail on any broadcast error

File: pkg/sync/sync_service.go [hunk 2]
```diff
@@ -294,6 +295,7 @@ func (syncService *SyncService[H]) setFirstAndStart(ctx context.Context, peerIDs
 //
 // `store` is closed last because it's used by other services.
 func (syncService *SyncService[H]) Stop(ctx context.Context) error {
+	syncService.topicSubscription.Cancel()
```
Comment (alpe) [inline pkg/sync/sync_service.go:298]: Without unsubscribe, the stop fails on the topic close.

File: node/full.go [hunk 3]
```diff
@@ -431,9 +408,12 @@ func (n *FullNode) Run(parentCtx context.Context) error {
 
 	// Perform cleanup
 	n.Logger.Info("halting full node and its sub services...")
+	// wait for all worker Go routines to finish so that we have
+	// no in-flight tasks while shutting down
+	wg.Wait()
```
Comment (alpe) [inline node/full.go:413]: Wait for the Go routines to complete to defined state, no WIP when stopped

File: node/full.go [hunk 4]
```diff
@@ -433,7 +401,7 @@ func (n *FullNode) Run(parentCtx context.Context) error {
 	n.Logger.Info("halting full node and its sub services...")
 
 	// Use a timeout context to ensure shutdown doesn't hang
-	shutdownCtx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
+	shutdownCtx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
```
[the remark this answers is not in the document]
Comment (alpe) [reply node/full.go:413]: 20s is an arbitrary number. Maybe 9s is a better fit?

**Review by tac0turtle — APPROVED** [review]
utack

File: node/full.go [hunk 5]
```diff
@@ -27,7 +28,7 @@ import (
 	"github.com/rollkit/rollkit/pkg/service"
 	"github.com/rollkit/rollkit/pkg/signer"
 	"github.com/rollkit/rollkit/pkg/store"
-	"github.com/rollkit/rollkit/pkg/sync"
+	rollkitSync "github.com/rollkit/rollkit/pkg/sync"
```
Comment (julienrbrt) [inline node/full.go:31]: tiny nit: package name full lowercase, i thought it was a variable when reading the code on gh because of this.

File: node/full.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (julienrbrt) [reply node/full.go:413]: 9s sounds sufficient yeah

File: pkg/sync/sync_service.go (hunk 2 above)
Comment (julienrbrt) [reply pkg/sync/sync_service.go:298]: should we add that as a code comment?

**Review by julienrbrt — APPROVED** [review]
lgtm!
