### PR TITLE
fix: way of updating config values with flags

### LINKED ISSUE #1705: Handle Rollkit flags in the CLI so they're set appropriately
As a follow up scope of work, we probably need to go through and make sure that all flags are handled. 
And with that, we probably would want some helper that can be called to pull all flags into the config.

_Originally posted by @MSevey in https://github.com/rollkit/rollkit/pull/1704#pullrequestreview-2113464874_

### PR DESCRIPTION
**Pull request by yarikbratashchuk**
Closes #1705 

## Summary by CodeRabbit

- **New Features**
  - Added new flags for specifying DA mempool TTL and block time in lazy mode for enhanced configuration flexibility.

- **Bug Fixes**
  - Improved node configuration handling by binding flags to Viper and updating default settings.

- **Tests**
  - Introduced tests to validate the parsing of command-line flags for node configuration.

- **Chores**
  - Updated dependencies to include `github.com/mitchellh/mapstructure v1.5.0` as a direct dependency.

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -111,6 +117,140 @@ func GetNodeConfig(nodeConf *NodeConfig, cmConf *cmcfg.Config) {
 	}
 }
 
+// UpdateNodeConfigWithFlags updates NodeConfig with values from command line flags.
+func UpdateNodeConfigWithFlags(nodeConf *NodeConfig, flags *pflag.FlagSet) (err error) {
```
Comment (tzdybal) [inline config/config.go:121]: As the update is done "in place" I think `*NodeConfig` should be receiver, not first argument.

File: config/config.go [hunk 2]
```diff
@@ -111,6 +117,140 @@ func GetNodeConfig(nodeConf *NodeConfig, cmConf *cmcfg.Config) {
...
+		}
+	}
+
+	updateStringFlag := func(flagName string, updateFunc func(string)) {
+		if flag := flags.Lookup(flagName); flag.Changed {
+			updateFunc(flag.Value.String())
+		}
+	}
+
+	updateDurationFlag := func(flagName string, updateFunc func(time.Duration) error) error {
```
Comment (tzdybal) [inline config/config.go:134]: All the lambdas provided as `updateFunc` unconditionally return `nil`, so we might as well remove this param.
```suggestion
	updateDurationFlag := func(flagName string, updateFunc func(time.Duration)) error {
```

File: config/config.go [hunk 3]
```diff
@@ -111,6 +117,140 @@ func GetNodeConfig(nodeConf *NodeConfig, cmConf *cmcfg.Config) {
 	}
 }
 
+// UpdateNodeConfigWithFlags updates NodeConfig with values from command line flags.
+func UpdateNodeConfigWithFlags(nodeConf *NodeConfig, flags *pflag.FlagSet) (err error) {
+	updateBoolFlag := func(flagName string, updateFunc func(bool)) {
+		if flag := flags.Lookup(flagName); flag.Changed {
+			updateFunc(flag.Value.String() == "true")
+		}
+	}
```
Comment (tzdybal) [inline config/config.go:126]: KISS: use pointers instead of lambdas. This simplifies the code a lot, especially at calling side.
```suggestion
	updateBoolFlag := func(flagName string, target *bool) {
		if flag := flags.Lookup(flagName); flag.Changed {
			*target = flag.Value.String() == "true"
		}
	}
```

File: config/config.go [hunk 4]
```diff
@@ -111,6 +117,140 @@ func GetNodeConfig(nodeConf *NodeConfig, cmConf *cmcfg.Config) {
 	}
 }
 
+// UpdateNodeConfigWithFlags updates NodeConfig with values from command line flags.
+func UpdateNodeConfigWithFlags(nodeConf *NodeConfig, flags *pflag.FlagSet) (err error) {
+	updateBoolFlag := func(flagName string, updateFunc func(bool)) {
+		if flag := flags.Lookup(flagName); flag.Changed {
+			updateFunc(flag.Value.String() == "true")
```
Comment (tzdybal) [inline config/config.go:124]: I think it would be good touse [`strconv.ParseBool`](https://pkg.go.dev/strconv#ParseBool) for better UX.

**Review by tzdybal — CHANGES_REQUESTED** [review]
I left comments to be addressed - they should be addressed where possible (not only in the mentioned functions).

Additionally, there are no unit tests.

**Review by gupadhyaya — COMMENTED** [review]
how do you plan on handling the comet flags? there are so many of them. i would prefer a better approach is there is one. can you investigate a bit more?

**Comment by gupadhyaya** [comment]
> how do you plan on handling the comet flags? there are so many of them. i would prefer a better approach is there is one. can you investigate a bit more?

may be use viper along with cobra to bind flags and extract. take a look at how cosmos-sdk does it: https://github.com/rollkit/cosmos-sdk/blob/main/server/util.go#L66

**Comment by gupadhyaya** [comment]
```
cmd := &cobra.Command{}
v := viper.GetViper()
v.BindPFlags(cmd.Flags())
nc := DefaultNodeConfig
nc.GetViperConfig(v) // this should populate the flags to nc
```

File: cmd/rollkit/commands/run_node.go [hunk 5]
```diff
@@ -305,5 +295,28 @@ func parseConfig(cmd *cobra.Command) error {
...
+	})
+	if err != nil {
+		return fmt.Errorf("unable to decode command flags into config: %w", err)
+	}
+
+	// handle rollkit node configuration
+	if err := nodeConfig.GetViperConfig(v); err != nil {
+		return fmt.Errorf("unable to decode command flags into nodeConfig: %w", err)
+	}
+
```
[the remark this answers is not in the document]
Comment (yarikbratashchuk) [reply cmd/rollkit/commands/run_node.go:320]: agh, yeah 

tested manually though

File: cmd/rollkit/commands/run_node.go [hunk 6]
```diff
@@ -305,5 +295,28 @@ func parseConfig(cmd *cobra.Command) error {
...
 		return fmt.Errorf("error in config file: %w", err)
 	}
+
+	v := viper.GetViper()
+	if err := v.BindPFlags(cmd.Flags()); err != nil {
+		return err
+	}
+
+	// unmarshal viper into config
+	err := v.Unmarshal(&config, func(c *mapstructure.DecoderConfig) {
```
Comment (gupadhyaya) [inline cmd/rollkit/commands/run_node.go:305]: does this pull all the cometbft flags? e.g., `--rpc.laddr`?

Comment (yarikbratashchuk) [reply cmd/rollkit/commands/run_node.go:305]: yes
but now the main problem is that in cometbft commands we have:
```
cmd.Flags().String("p2p.external-address", config.P2P.ExternalAddress, "ip:port address to advertise to peers for them to dial")
```
and in cometbft config:
```
xternalAddress string `mapstructure:"external_address"`
```

Comment (yarikbratashchuk) [reply cmd/rollkit/commands/run_node.go:314]: added separate handling

**Review by MSevey — APPROVED** [review]

**Review by Manav-Aggarwal — APPROVED** [review]

File: cmd/rollkit/commands/run_node.go [hunk 7]
```diff
@@ -305,5 +295,42 @@ func parseConfig(cmd *cobra.Command) error {
...
+		c.TagName = "mapstructure"
+		c.DecodeHook = mapstructure.ComposeDecodeHookFunc(
+			mapstructure.StringToTimeDurationHookFunc(),
+			mapstructure.StringToSliceHookFunc(","),
```
Comment (tzdybal) [inline cmd/rollkit/commands/run_node.go:318]: :exploding_head:

**Review by tzdybal — APPROVED** [review]
