### PR TITLE
fix: use batchtime from sequencer for header time, upgrade to latest go-da and go-sequencing

### LINKED ISSUE #1842: chore: use batch time from the sequencer to initialize block/header time
sequencer `GetNextBatch` returns batch time which needs to be used in publish block

### PR DESCRIPTION
**Pull request by gupadhyaya**
Fixes #1842 

## Release Notes

- **New Features**
	- Enhanced transaction and batch management, including improved timestamp handling.
	- Improved handling of chain IDs in tests for better accuracy across multiple chain contexts.

- **Tests**
	- Added new test cases for mempool behavior across nodes and block processing time constraints.
	- Updated existing tests to improve assertions and ensure comprehensive coverage of functionalities.
	- Increased timeout duration in tests to accommodate longer processing times.

- **Chores**
	- Updated dependency versions for better compatibility and performance, including `github.com/rollkit/go-sequencing` to version `v0.2.1-0.20241010053131-3134457dc4e5`.
	- Retraction notice added for version `v0.12.0` due to accidental publication.

### CODE REVIEW

File: block/manager.go [hunk 1]
```diff
@@ -415,20 +415,24 @@ func (m *Manager) BatchRetrieveLoop(ctx context.Context) {
...
+				// Add the batch to the batch queue
+				if batch != nil && batch.Transactions != nil {
+					m.bq.AddBatch(BatchWithTime{batch, batchTime})
+					// Calculate the hash of the batch and store it for the next batch retrieval
+					batchBytes, err := batch.Marshal()
+					if err != nil {
+						m.logger.Error("error while marshaling batch", "error", err)
+					}
+					h := sha256.Sum256(batchBytes)
+					m.lastBatchHash = h[:]
```
Comment (tzdybal) [inline block/manager.go:434]: You should use `Batch.Hash`

File: block/manager.go [hunk 2]
```diff
@@ -984,16 +988,16 @@ func (m *Manager) getSignature(header types.Header) (*types.Signature, error) {
 	return &signature, nil
 }
 
-func (m *Manager) getTxsFromBatch() cmtypes.Txs {
+func (m *Manager) getTxsFromBatch() (cmtypes.Txs, time.Time) {
 	batch := m.bq.Next()
 	if batch == nil {
-		return make(cmtypes.Txs, 0)
+		return make(cmtypes.Txs, 0), time.Now()
```
Comment (tzdybal) [inline block/manager.go:994]: This implicitly requires that sequencer and rollkit use synchronized clocks, right?

**Review by tzdybal — CHANGES_REQUESTED** [review]
Please use newly introduced `Hash` method instead of computing hash inline.

File: block/manager.go (hunk 1 above)
Comment (gupadhyaya) [reply block/manager.go:434]: good catch.

File: block/manager.go (hunk 2 above)
Comment (gupadhyaya) [reply block/manager.go:994]: i think this is little bit tricky. there is no batch coming from the sequencer and rollkit wants to create empty headers. not sure how to tackle this. any suggestions?

Comment (gupadhyaya) [reply block/manager.go:997]: modified little bit to add empty batch to queue so that we can extract the sequencer timestamps and use it for empty batches as well. 
the only case remains is when the batch is `nil`, which can only happen if the batch retrieval is set to slow and blocktime is faster. currently this cannot happen either, as we are using blocktime as default batch retrieval time and it is not configurable presently.

Comment (gupadhyaya) [reply block/manager.go:997]: may be it is more correct to `panic` if we encounter `batch == nil` to prevent inconsistent timestamping. what we want is always have sequencer timestamp.

Comment (MSevey) [reply block/manager.go:997]: Can we write a test? The test updates for this feel surface level so the fix is covering a case that we weren't testing previously I assume.

**Review by MSevey — COMMENTED** [review]
Will review again after test is written

File: block/manager.go (hunk 2 above)
Comment (gupadhyaya) [reply block/manager.go]: ok. handled it slightly differently. `getTxsFromBatch` will return `ErrNoBatch` and `publishBlock` will also error out without proceeding with block creation. this should work?

File: block/manager.go [hunk 3]
```diff
@@ -53,7 +52,7 @@ const defaultBlockTime = 1 * time.Second
 const defaultLazyBlockTime = 60 * time.Second
 
 // defaultBatchRetrievalInterval is the interval at which the sequencer retrieves batches
-const defaultBatchRetrievalInterval = 1 * time.Second
+const defaultBatchRetrievalInterval = 100 * time.Microsecond
```
Comment (gupadhyaya) [inline block/manager.go:55]: when empty block production, we need to make the batch retrieval faster than the blocktime. this should be configurable in the future: https://github.com/rollkit/rollkit/issues/1832

Comment (MSevey) [reply block/manager.go:55]: `Microsecond` is a little aggressive isn't it? That's going to be causing the batch retrieve loop to be cycling basically constantly. 

`Milliseconds` should be fine. If the default block time is 1s then we are still doing batches 10x faster than the block time. 

Or we should make this a factor of the block time with a maximum value. Which could eliminate the need for it to be configurable. 

Then we set it on initialization of the manager. 

something like
```go
const maxBatchRetrievalInterval = 100 time.Millisecond
const BatchRetrievalFactor = 10
func calcBatchRetrievalInterval(blockTime time.Duration) time.Duration {
   interval := blockTime / 10
   if interval > maxBatchRetrievalInterval {
      return maxBatchRetrievalInterval
   }
   return interval
}
```

**Review by MSevey — APPROVED** [review]

**Comment by gupadhyaya** [comment]
there is still a failing test which I am trying to fix. hold on.

File: block/manager.go (hunk 3 above)
Comment (gupadhyaya) [reply block/manager.go]: decided to use the blocktime.

**Review by tzdybal — APPROVED** [review]
I'm mot a big fan of large timeouts in tests, but I guess that it's needed in CI.

**Review by MSevey — APPROVED** [review]

**Review by Manav-Aggarwal — APPROVED** [review]
utAck
