### PR TITLE
test: fix genesis validator set helper

### LINKED ISSUE #860: test: use const for genesis validator set
In `full_client_test.go` we have `getGenesisValidatorSetWithSigner`. We can possibly replace this with consts for GEN_VAL_SET and GEN_KEY.

### PR DESCRIPTION
**Pull request by tuxcanfly**
## Overview

This PR removes a `TODO` in the test helper `getGenesisValidatorSetWithSigner`. This helper should only ever called with `n=1`. The validator set and key are structs, so they can't be `consts`.

Closes: #860 

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

## Summary by CodeRabbit

- **Refactor**
	- Updated the genesis validator generation process to support multiple validators.
- **Tests**
	- Adjusted test functions to accommodate the updated genesis validator generation process.

### CODE REVIEW

File: node/test_helpers.go [hunk 1]
```diff
@@ -117,16 +117,21 @@ func waitForAtLeastNBlocks(node Node, n int, source Source) error {
 	})
 }
 
-// TODO: use n and return n validators
```
Comment (MSevey) [inline node/test_helpers.go:120]: I think this is a right direction long term for this helper, but in the short term we only support 1 validator right? Or is it multiple validators, but 1 sequencer?

File: node/test_helpers.go [hunk 2]
```diff
@@ -117,16 +117,21 @@ func waitForAtLeastNBlocks(node Node, n int, source Source) error {
...
 func getGenesisValidatorSetWithSigner(n int) ([]cmtypes.GenesisValidator, crypto.PrivKey) {
 	nodeKey := &p2p.NodeKey{
 		PrivKey: genesisValidatorKey,
 	}
 	signingKey, _ := GetNodeKey(nodeKey)
 	pubKey := genesisValidatorKey.PubKey()
```
Comment (MSevey) [inline node/test_helpers.go:126]: Building on the coderabbitai comment, all of this should be within the for loop so that validators have unique keys.

File: node/test_helpers.go (hunk 1 above)
Comment (Manav-Aggarwal) [reply node/test_helpers.go:120]: Agreed, should just support 1 validator. The validator set is the same as the sequencer set here.

Comment (tuxcanfly) [reply node/test_helpers.go:120]: Agreed, I think it's best to remove `n` argument and just return a validator set containing one validator always.

File: node/test_helpers.go (hunk 2 above)
Comment (tuxcanfly) [reply node/test_helpers.go:126]: Removed the for loop as we will only return one validator.

**Review by Manav-Aggarwal — APPROVED** [review]
Thanks, LGTM!

**Review by nashqueue — APPROVED** [review]
